/*
 * @Author: tohsaka888
 * @Date: 2022-08-01 11:31:01
 * @LastEditors: tohsaka888
 * @LastEditTime: 2022-08-19 15:12:28
 * @Description: 请填写简介
 */
import { Layout } from 'antd'
import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import { Suspense, useCallback, useEffect, useReducer, useState } from 'react'
import { Graph } from '..'
import Canvas from '../components/KnowledgeMap/index'
import { baseUrl } from '../config/baseUrl'
import useScreenSize from '../hooks/useScreenSize'
import { nodeRadius, basicDistence, arcAreaLength, arcAreaDistence, mode } from '../components/KnowledgeMap/defaultConfig'
import { ConfigContext } from '../context'
import { VisibleContext } from '../components/context'
import ControllerPannel from '../components/ControllerPannel'
import main from '../mock/main.json'

const initState: Graph.ConfigProps = {
  nodeRadius,
  basicDistence,
  arcAreaDistence,
  arcAreaLength,
  mode: 2,
  showDisctription: true,
  isStraight: true,
  besselRate: 5,
  lineWidth: 1,
  arrowPosition: 50
}

const reducer = (state: typeof initState, action: Graph.ActionType) => {
  switch (action.type) {
    case 'setMode':
      return { ...state, mode: action.payload }
    case 'setAreaLength':
      return { ...state, arcAreaLength: action.payload }
    case 'setAreaDistence':
      return { ...state, arcAreaDistence: action.payload }
    case 'setNodeRadius':
      return { ...state, nodeRadius: action.payload }
    case 'setBasicDistence':
      return { ...state, basicDistence: action.payload }
    case 'setShowDiscription':
      return { ...state, showDisctription: action.payload }
    case 'setIsStraight':
      return { ...state, isStraight: action.payload }
    case 'setBesselRate':
      return { ...state, besselRate: action.payload }
    case 'setLineWidth':
      return { ...state, lineWidth: action.payload }
    case 'setArrowPosition':
      return { ...state, arrowPosition: action.payload }
  }
}

const Home: NextPage = () => {
  const { height } = useScreenSize()
  const [config, dispatch] = useReducer(reducer, initState)
  const [visible, setVisible] = useState<boolean>(false)
  const [graphData, setGraphData] = useState<{ nodes: Graph.Node[]; edges: Graph.Edge[]; }>({ nodes: [], edges: [] })
  const [insideGraph, setInsideGraph] = useState<{ vertices: Graph.Vertice[]; edges: Graph.Line[]; }>({ vertices: [], edges: [] })
  const [outsideGraph, setOutsideGraph] = useState<{ vertices: Graph.Vertice[]; edges: Graph.Line[]; }>({ vertices: [], edges: [] })
  const [loading, setLoading] = useState<boolean>(true)

  const getData = useCallback(async () => {
    const inRes = await fetch(`${baseUrl}/api/getNextVerticesWithEdge?id=${main.id}&direction=in`)
    const inData: Api.KnowledgeResponse = await inRes.json()
    setInsideGraph(inData.data)

    const outRes = await fetch(`${baseUrl}/api/getNextVerticesWithEdge?id=${main.id}&direction=out`)
    const outData: Api.KnowledgeResponse = await outRes.json()
    setOutsideGraph(outData.data)

    setLoading(false)
  }, [])

  useEffect(() => {
    getData()
  }, [getData])

  return (
    <>
      <Head>
        <title>知识图谱</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Layout>
          <Layout.Header>
            <h1 style={{ color: '#fff' }}>知识图谱Demo</h1>
          </Layout.Header>
          <Layout style={{ minHeight: height - 70 }}>
            <ConfigContext.Provider value={{ config, dispatch }}>
              <Layout.Sider theme={'light'} style={{ minHeight: '90vh' }}>
                <ControllerPannel />
              </Layout.Sider>
              <Layout.Content style={{ height: height - 70 }}>
                <VisibleContext.Provider value={{ visible, setVisible }}>
                  {!loading && <Canvas
                    insideVertices={insideGraph.vertices}
                    mainVertice={main}
                    outsideVertices={outsideGraph.vertices}
                    nodes={graphData.nodes}
                    edges={[...insideGraph.edges, ...outsideGraph.edges]}
                    config={config}
                  />}
                </VisibleContext.Provider>
              </Layout.Content>
            </ConfigContext.Provider>
          </Layout>
        </Layout>
      </main>
    </>
  )
}

// export const getServerSideProps: GetServerSideProps = async () => {
//   const res = await fetch(`${baseUrl}/api/graph`)
//   const data: Api.GraphResponse = await res.json()
//   return {
//     props: {
//       data: data.data
//     },
//   }
// }

export default Home
